In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from category_encoders import target_encoder, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
import pandas as pd

In [24]:
df=pd.read_csv('Student_Performance1.csv')
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [25]:
X= df.drop(columns=['Performance Index'])
Y=df['Performance Index']

In [26]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,train_size=0.8,random_state=42)

In [27]:
xtrain

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
9254,5,49,No,7,5
1561,2,48,Yes,7,6
1670,2,81,No,7,2
6087,2,46,No,6,1
6669,8,47,No,9,0
...,...,...,...,...,...
5734,8,50,Yes,6,6
5191,4,68,No,9,3
5390,9,48,No,7,6
860,1,47,No,9,0
7270,2,46,No,6,6

In [28]:
ytrain

9254    36.0
1561    25.0
1670    59.0
6087    22.0
6669    40.0
        ...
5734    48.0
5191    51.0
5390    44.0
860     20.0
7270    24.0
Name: Performance Index, Length: 8000, dtype: float64

In [29]:
xtest

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
6252,5,69,No,8,2
4684,2,46,Yes,4,8
1731,7,56,Yes,7,5
4742,6,42,Yes,8,5
4521,7,53,No,4,6
...,...,...,...,...,...
6412,2,70,No,7,3
8285,4,79,No,9,3
7853,2,40,Yes,7,2
1095,3,83,No,7,5
6929,5,60,No,8,4

In [30]:
ytest

6252    51.0
4684    20.0
1731    46.0
4742    28.0
4521    41.0
        ...
6412    45.0
8285    66.0
7853    16.0
1095    65.0
6929    47.0
Name: Performance Index, Length: 2000, dtype: float64

In [31]:
num_cols=X.select_dtypes(include='number').columns
obj_cols=X.select_dtypes(include='object').columns

In [35]:
from sklearn.compose import ColumnTransformer
preprocessing= ColumnTransformer(
    transformers=[
        ('scaling', StandardScaler(), num_cols),
        ('encoder', OneHotEncoder(handle_unknown='indicator'), obj_cols)
    ]


)

updated_xtrain = preprocessing.fit_transform(xtrain)
preprocessing

ColumnTransformer(transformers=[('scaling', StandardScaler(),
                                 Index(['Hours Studied', 'Previous Scores', 'Sleep Hours',
       'Sample Question Papers Practiced'],
      dtype='object')),
                                ('encoder',
                                 OneHotEncoder(handle_unknown='indicator'),
                                 Index(['Extracurricular Activities'], dtype='object'))])