In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv('loan_data.csv')
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [3]:
x=df.drop(columns=['loan_status'])
y=df['loan_status']

In [4]:
num_cols=x.select_dtypes(include='number').columns
x=x[num_cols]

In [5]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y, random_state=42, train_size=0.8)

In [6]:
gridsearch=GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid={
        'criterion':['gini','entropy'],
        'splitter':['best','random'],
        'max_depth':[None,5,10,20],
        'min_samples_split':[2,3,5,7],
        'min_samples_leaf':[1,3,5,7],
        'max_features':['auto','sqrt','log2']
    },
    cv=3,
    verbose=1,
    error_score='raise'
)
gridsearch.fit(xtrain,ytrain)

Fitting 3 folds for each of 768 candidates, totalling 2304 fits

InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

In [ ]:
model=gridsearch.best_estimator_

In [ ]:
model.fit(xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy', max_depth=10, max_features='log2',
                       min_samples_leaf=3, random_state=42)

In [ ]:
gridsearch.best_params_

In [ ]:
gridsearch.cv_results_

{'mean_fit_time': array([0.00240736, 0.00219016, 0.00263233, 0.00249705, 0.00262275,
        0.0026938 , 0.00200109, 0.00262089, 0.0018898 , 0.00241323,
        0.00223427, 0.00279355, 0.00239878, 0.00230188, 0.00200505,
        0.00259771, 0.00200362, 0.00219626, 0.00199971, 0.00200419,
        0.00198493, 0.00219979, 0.00179944, 0.00221953, 0.00202985,
        0.00199003, 0.00211449, 0.00182772, 0.00201049, 0.00241199,
        0.00239873, 0.002178  , 0.07199273, 0.0300355 , 0.06932068,
        0.02945623, 0.0678472 , 0.02605152, 0.07072992, 0.02554412,
        0.06756849, 0.0178791 , 0.06789432, 0.01752949, 0.06979713,
        0.01835461, 0.06622453, 0.01933489, 0.06508913, 0.01357336,
        0.06455922, 0.01111279, 0.06286483, 0.0111196 , 0.06139898,
        0.01205668, 0.06032391, 0.01020751, 0.05896101, 0.01036019,
        0.06017623, 0.0101542 , 0.05885921, 0.01042705, 0.09729695,
        0.03369398, 0.09973402, 0.03201342, 0.09808602, 0.03011217,
        0.09426193, 0.02870808, 0.09332805, 0.02755437, 0.09351478,
        0.02717371, 0.09474692, 0.02681394, 0.0925601 , 0.02607889,
        0.08874249, 0.02383871, 0.087573  , 0.02414846, 0.09195967,
        0.02351913, 0.09103975, 0.02370753, 0.08971834, 0.02300205,
        0.08939452, 0.02387338, 0.08933954, 0.02276192, 0.08907385,
        0.02256103, 0.00198169, 0.00199437, 0.00221047, 0.00222707,
        0.00218563, 0.00220809, 0.00200081, 0.00261621, 0.00237656,
        0.002316  , 0.00221977, 0.00200491, 0.00221472, 0.00220461,
        0.00241752, 0.00260711, 0.00203691, 0.00240417, 0.00221648,
        0.00220351, 0.00221772, 0.00211787, 0.00200248, 0.00221372,
        0.00201373, 0.0020329 , 0.00202465, 0.00198665, 0.00214772,
        0.00200167, 0.00199289, 0.00240841, 0.02861657, 0.00940156,
        0.02896962, 0.00955086, 0.02893753, 0.00951314, 0.0287611 ,
        0.0098474 , 0.02851133, 0.00902424, 0.02866154, 0.00892124,
        0.02855601, 0.00891891, 0.02858047, 0.00901127, 0.02869434,
        0.00820045, 0.02896233, 0.00823498, 0.02859359, 0.00847154,
        0.0289011 , 0.00830116, 0.02891245, 0.0081995 , 0.0289566 ,
        0.00820885, 0.0286859 , 0.00818963, 0.02909036, 0.00806608,
        0.03106551, 0.00973992, 0.0311254 , 0.00984521, 0.03138728,
        0.01046257, 0.03109612, 0.00981579, 0.03150892, 0.01023645,
        0.03229532, 0.00984173, 0.0315568 , 0.01027532, 0.03157487,
        0.00981383, 0.03134894, 0.00994287, 0.03268642, 0.01023297,
        0.03168349, 0.0100028 , 0.03230085, 0.00955396, 0.03126712,
        0.0099997 , 0.03221316, 0.01021581, 0.03203101, 0.01001577,
        0.03178453, 0.00968261, 0.00220885, 0.00219913, 0.00219579,
        0.00202422, 0.00222197, 0.0021975 , 0.0026134 , 0.00240068,
        0.00198178, 0.00201898, 0.00200143, 0.00219545, 0.00220618,
        0.00220065, 0.00200133, 0.00240541, 0.00202041, 0.00204   ,
        0.00218868, 0.00199351, 0.00238643, 0.00201488, 0.002033  ,
        0.00203085, 0.00257301, 0.00219593, 0.00200119, 0.0021935 ,
        0.00219913, 0.00232291, 0.00220404, 0.00200787, 0.04289994,
        0.01197467, 0.04113574, 0.01172566, 0.04179344, 0.01265607,
        0.04237013, 0.01201282, 0.04043398, 0.01073098, 0.04021611,
        0.01099606, 0.03981628, 0.01035213, 0.04053183, 0.01071234,
        0.04089212, 0.00832891, 0.04116206, 0.00827441, 0.04135199,
        0.00922046, 0.04253793, 0.00899367, 0.04066086, 0.0085803 ,
        0.04094143, 0.00891728, 0.04121294, 0.00853181, 0.04076095,
        0.00876045, 0.05825682, 0.01335106, 0.05849323, 0.01295815,
        0.05901351, 0.01320086, 0.05958319, 0.01243353, 0.05787177,
        0.01345673, 0.05794678, 0.01323462, 0.05819545, 0.01342082,
        0.05867891, 0.01342506, 0.06419587, 0.01325817, 0.05952797,
        0.01323137, 0.05886292, 0.01409574, 0.06081061, 0.01348271,
        0.06085496, 0.01323047, 0.06103892, 0.01302967, 0.06099944,
        0.01343727, 0.06099443, 0.01296501, 0.00240173, 0.00244999,
        0.00223618, 0.00198569, 0.00219555, 0.00217557, 0.00220971,
        0.00202198, 0.00202146, 0.0022296 , 0.00200377, 0.00239778,
        0.00222716, 0.00219975, 0.0021132 , 0.00219445, 0.00220103,
        0.00219531, 0.00198545, 0.00200658, 0.00233598, 0.00201378,
        0.00201364, 0.00199361, 0.0024035 , 0.002005  , 0.00191803,
        0.00200181, 0.00222144, 0.00222592, 0.00241699, 0.00220938,
        0.06542325, 0.02173352, 0.0661037 , 0.02190633, 0.06297731,
        0.02089086, 0.06443028, 0.02031822, 0.06186666, 0.01532578,
        0.06262178, 0.01705294, 0.06414151, 0.01550245, 0.06250343,
        0.01531134, 0.06059756, 0.01029749, 0.0598434 , 0.010179  ,
        0.06077557, 0.01011848, 0.05970144, 0.01017776, 0.05898643,
        0.01041293, 0.05881553, 0.01016603, 0.05893259, 0.00995631,
        0.05872235, 0.01022272, 0.09306245, 0.02515659, 0.09305515,
        0.02637792, 0.0920835 , 0.0245204 , 0.09099169, 0.02326603,
        0.0893713 , 0.02217145, 0.08955092, 0.023527  , 0.09123192,
        0.02224221, 0.08917599, 0.02248702, 0.08779926, 0.02135024,
        0.0872344 , 0.02140102, 0.08661952, 0.02058415, 0.08688908,
        0.02069197, 0.08693042, 0.01832643, 0.08744969, 0.01862464,
        0.08638601, 0.01849389, 0.08989773, 0.01853747, 0.00218501,
        0.00259786, 0.00194354, 0.00218372, 0.00218801, 0.00238271,
        0.00240083, 0.00199904, 0.00180411, 0.00220304, 0.00220056,
        0.00220189, 0.00240173, 0.00220146, 0.00192652, 0.00178409,
        0.00221925, 0.0023983 , 0.00219822, 0.00220156, 0.0021184 ,
        0.00198469, 0.002356  , 0.0021934 , 0.00218062, 0.00221467,
        0.00238128, 0.00239844, 0.00219913, 0.00221291, 0.00237894,
        0.00222263, 0.08384638, 0.03190536, 0.08491917, 0.03040915,
        0.0813828 , 0.02768416, 0.0815362 , 0.02684994, 0.07949696,
        0.01800108, 0.07914829, 0.01842566, 0.07833409, 0.0177578 ,
        0.07481031, 0.017839  , 0.07549858, 0.01059146, 0.07622657,
        0.01042151, 0.07606626, 0.01033468, 0.07544212, 0.01060996,
        0.06844039, 0.01014361, 0.06900673, 0.01062069, 0.0687068 ,
        0.01015601, 0.06824913, 0.0106585 , 0.11416869, 0.03612056,
        0.11790724, 0.03448544, 0.11633892, 0.03306479, 0.11554985,
        0.03008642, 0.10724225, 0.02713828, 0.10901194, 0.02849512,
        0.10670877, 0.02700763, 0.10955462, 0.02665997, 0.10593619,
        0.02366972, 0.10652027, 0.02353458, 0.10529447, 0.02826748,
        0.11125431, 0.02461433, 0.10056939, 0.02270656, 0.09958348,
        0.02248964, 0.10087957, 0.0229753 , 0.10013738, 0.02235637,
        0.00219779, 0.00239687, 0.00199656, 0.00211787, 0.00241499,
        0.00199256, 0.00219307, 0.00219655, 0.00223336, 0.00211864,
        0.00220561, 0.00238361, 0.00219469, 0.00200996, 0.00219493,
        0.00218525, 0.00209627, 0.00220766, 0.00219312, 0.00200047,
        0.00220037, 0.00221324, 0.00191584, 0.00220022, 0.00221167,
        0.00242066, 0.00241785, 0.00219073, 0.00235777, 0.00219984,
        0.00241113, 0.00218787, 0.03208199, 0.00935664, 0.03215861,
        0.00953789, 0.03226514, 0.00981617, 0.0324975 , 0.00932927,
        0.03154616, 0.00940261, 0.03163929, 0.00911069, 0.03162384,
        0.00912652, 0.03190708, 0.00920668, 0.031879  , 0.00804615,
        0.03203564, 0.00789647, 0.03149137, 0.00803299, 0.03209519,
        0.00808592, 0.03193092, 0.00794969, 0.03191218, 0.00802116,
        0.03205848, 0.00792656, 0.03291569, 0.00838675, 0.03644481,
        0.0103467 , 0.03675365, 0.00941763, 0.03629284, 0.01002913,
        0.03636522, 0.0098268 , 0.03642616, 0.00981021, 0.03589215,
        0.01035404, 0.03670483, 0.00971298, 0.03618445, 0.00981812,
        0.03604684, 0.00992389, 0.0363946 , 0.00980177, 0.03671608,
        0.01022058, 0.03603811, 0.00992713, 0.036445  , 0.01022134,
        0.03662276, 0.01024375, 0.03666425, 0.00982189, 0.03628497,
        0.00976534, 0.00199184, 0.00218554, 0.00240145, 0.00225205,
        0.00209136, 0.0024065 , 0.00220032, 0.00239897, 0.00240216,
        0.00229182, 0.0021884 , 0.0026042 , 0.00199585, 0.00201225,
        0.00239143, 0.00179906, 0.00219669, 0.00220585, 0.00219212,
        0.00199943, 0.00202384, 0.00240221, 0.00201297, 0.00219269,
        0.00199361, 0.00240235, 0.00219679, 0.00239983, 0.00230255,
        0.00220103, 0.0022191 , 0.00237937, 0.04895291, 0.01234398,
        0.04971328, 0.01214375, 0.04883127, 0.01180391, 0.04812536,
        0.01172891, 0.04834046, 0.01059475, 0.04902444, 0.01050172,
        0.04888735, 0.01074295, 0.04937749, 0.010782  , 0.04745941,
        0.00888624, 0.04758739, 0.00864611, 0.04667211, 0.00861068,
        0.04668064, 0.00858269, 0.04798775, 0.00877771, 0.04741077,
        0.00823207, 0.0475533 , 0.0084013 , 0.04919262, 0.00900755,
        0.07144132, 0.01270847, 0.06962233, 0.01391077, 0.07693362,
        0.01404481, 0.07798266, 0.01350737, 0.07504487, 0.01382742,
        0.07534704, 0.01308141, 0.07351804, 0.0173368 , 0.07529182,
        0.01288047, 0.07665281, 0.01370549, 0.07205644, 0.01287813,
        0.07057323, 0.01242528, 0.07094464, 0.01236758, 0.07183404,
        0.01390243, 0.07303729, 0.01360826, 0.07291412, 0.01435537,
        0.07708874, 0.01273608, 0.00219264, 0.00256681, 0.00200233,
        0.00219345, 0.00237269, 0.00240126, 0.00260148, 0.0022284 ,
        0.00240045, 0.00218425, 0.00190306, 0.00220509, 0.00223131,
        0.00198603, 0.00208359, 0.00199866, 0.00214157, 0.00219994,
        0.00199027, 0.00221515, 0.00238571, 0.00223064, 0.00221443,
        0.0022028 , 0.00219254, 0.00218334, 0.00200195, 0.00239854,
        0.00221653, 0.00229497, 0.00201106, 0.00240126, 0.07563396,
        0.02334909, 0.07782354, 0.02235003, 0.07778254, 0.02140675,
        0.07610264, 0.02186437, 0.07376633, 0.01576099, 0.07304616,
        0.01608458, 0.07759309, 0.01561885, 0.07492104, 0.01533785,
        0.07545438, 0.01053176, 0.07153268, 0.00996499, 0.06932368,
        0.00952249, 0.06954317, 0.00941997, 0.07191644, 0.00964184,
        0.06816516, 0.00954127, 0.0683547 , 0.00931053, 0.06777349,
        0.00939503, 0.10913439, 0.02335672, 0.10558119, 0.02606311,
        0.12014055, 0.02493472, 0.11454535, 0.02423534, 0.11238141,
        0.02274327, 0.10289969, 0.02254896, 0.10194893, 0.02309399,
        0.10067625, 0.02221661, 0.10711355, 0.02184286, 0.09979839,
        0.02109709, 0.0988946 , 0.020961  , 0.09838204, 0.02109094,
        0.09791751, 0.01974344, 0.09820018, 0.01954026, 0.09858074,
        0.02050924, 0.09931493, 0.02071581]),
 'std_fit_time': array([4.93776779e-04, 4.40849077e-04, 4.91715009e-04, 4.47511853e-04,
        7.85780206e-04, 4.05252862e-04, 1.03610910e-05, 4.54982050e-04,
        1.89414437e-04, 4.82069547e-04, 7.23144112e-04, 7.36275484e-04,
        4.88782984e-04, 3.94595192e-04, 9.17388098e-06, 1.01615724e-03,
        5.41666863e-06, 4.02757547e-04, 1.11130682e-05, 8.42721151e-06,
        2.52487864e-05, 3.65447034e-04, 3.77806016e-04, 3.87234979e-04,
        3.05802477e-05, 1.60194577e-05, 4.67650720e-04, 4.11370266e-04,
        1.22470126e-05, 5.14667303e-04, 4.91061227e-04, 3.90887690e-04,
        3.76677851e-03, 1.45530516e-03, 3.18721005e-03, 6.82090139e-04,
        5.58753530e-04, 1.01603291e-03, 2.80619733e-03, 9.18988171e-04,
        2.73989336e-03, 4.86150707e-03, 2.91175923e-03, 5.08901084e-03,
        3.45413403e-03, 5.13024342e-03, 2.67995965e-03, 5.46412499e-03,
        2.88699099e-03, 1.38232072e-03, 2.71961898e-03, 6.68989186e-04,
        1.04442958e-03, 2.14789868e-04, 1.54009458e-03, 2.18074302e-03,
        2.11152519e-03, 3.85979684e-04, 1.72009515e-03, 4.26978891e-04,
        1.73841739e-03, 2.27248873e-04, 1.76277474e-03, 3.87146535e-04,
        1.64175468e-03, 5.90364408e-04, 1.39833577e-03, 5.69934953e-04,
        2.39194831e-03, 7.81855358e-04, 3.21652359e-03, 6.29556519e-04,
        5.14139995e-03, 4.66876923e-04, 4.91682664e-03, 7.31574804e-04,
        4.99136553e-03, 8.12669925e-04, 2.38911164e-03, 3.04926957e-04,
        3.64738475e-03, 5.45858312e-04, 2.29044925e-03, 2.37155893e-03,
        9.25112893e-03, 4.61182558e-04, 8.53235343e-03, 7.32044275e-04,
        2.82154851e-03, 6.53957270e-04, 1.77560851e-03, 5.95115400e-04,
        1.59702122e-03, 1.12771968e-03, 2.38373267e-03, 8.43985396e-04,
        3.56278736e-05, 8.79953953e-04, 4.11771363e-04, 3.92281848e-04,
        3.77336142e-04, 4.01335529e-04, 7.02586827e-06, 5.63404107e-04,
        7.72687992e-04, 3.83590673e-04, 4.10248605e-04, 1.38006263e-05,
        4.28625614e-04, 3.60871243e-04, 5.09060514e-04, 5.04476113e-04,
        3.65313284e-05, 5.42140162e-04, 4.24158180e-04, 3.82740063e-04,
        4.23695760e-04, 4.89818145e-04, 9.71274101e-06, 4.41767766e-04,
        3.79304103e-05, 3.93939647e-05, 2.48221108e-05, 2.42646870e-05,
        6.85864796e-04, 6.28991856e-04, 1.56816366e-05, 4.90686719e-04,
        3.72266027e-04, 4.84671160e-04, 3.23256262e-04, 4.52515333e-04,
        1.17574294e-04, 6.59613806e-04, 4.92925564e-04, 4.29287810e-04,
        4.72813784e-04, 5.24556852e-05, 5.63413328e-04, 9.95634977e-04,
        4.62389157e-04, 4.87496879e-04, 4.41004449e-04, 9.09192151e-04,
        3.26081715e-04, 4.06669793e-04, 9.43006696e-05, 4.34308037e-04,
        5.80290376e-04, 7.61917792e-04, 4.68177070e-04, 4.09082725e-04,
        4.51450565e-04, 4.03174302e-04, 7.21469849e-04, 4.40656634e-04,
        6.51906061e-04, 4.03951196e-04, 3.22245916e-04, 4.92040142e-04,
        6.01483144e-04, 3.56855620e-04, 5.53535211e-04, 3.89674243e-04,
        3.76106329e-04, 5.11158967e-04, 7.16108840e-04, 4.15846255e-04,
        6.55058437e-04, 3.81103799e-04, 9.64459759e-04, 4.12708535e-04,
        4.45034381e-04, 4.11527690e-04, 1.34540786e-03, 3.72587978e-04,
        5.40670744e-04, 1.37700598e-04, 3.90493370e-04, 4.64130946e-04,
        3.71340971e-04, 6.54698606e-04, 1.32593764e-03, 4.40865606e-04,
        6.35431726e-04, 5.10327158e-06, 1.44303975e-03, 1.45426946e-03,
        2.56021388e-04, 6.33833403e-04, 4.49314700e-04, 5.57010615e-04,
        3.92702790e-04, 3.89307868e-04, 3.76471691e-04, 2.44396605e-05,
        3.55638681e-04, 3.62648876e-04, 4.96734032e-04, 4.83870243e-04,
        3.99119823e-05, 3.06381882e-05, 3.42062119e-06, 4.06076456e-04,
        3.97174973e-04, 3.85662798e-04, 1.53230269e-05, 4.90695324e-04,
        2.15303462e-05, 2.76061948e-05, 3.90252165e-04, 1.61904297e-05,
        4.96112700e-04, 3.08388695e-05, 3.39433040e-05, 6.05422340e-04,
        4.71926075e-04, 4.01760324e-04, 6.32108466e-04, 3.83950079e-04,
        3.93067643e-04, 6.04233872e-04, 7.15094287e-04, 3.48947725e-05,
        2.06928927e-03, 1.25461067e-04, 7.90497693e-04, 3.99407184e-04,
        1.23465831e-03, 7.95757239e-04, 1.91138479e-03, 6.26588967e-04,
        1.57215525e-03, 1.65794946e-03, 2.34095799e-03, 1.67303006e-03,
        9.67026269e-04, 1.92237122e-03, 8.61457491e-04, 1.47347481e-03,
        1.12870775e-03, 5.67125027e-04, 1.53335909e-03, 6.47433500e-04,
        1.06943361e-03, 1.49682544e-03, 2.06406912e-03, 5.88582945e-04,
        4.68780572e-04, 5.05414966e-04, 1.12426146e-03, 7.70732218e-04,
        8.75243724e-04, 4.46289547e-04, 9.95868559e-04, 3.78868683e-04,
        1.67250603e-03, 5.79448987e-04, 2.19657608e-03, 1.50155302e-04,
        1.15814932e-03, 4.24226522e-04, 2.01428973e-03, 4.72946795e-04,
        6.68343497e-04, 4.78326132e-04, 1.83202706e-03, 7.61417839e-04,
        1.57904002e-03, 5.03790971e-04, 1.96176308e-03, 7.96597689e-04,
        1.28663332e-02, 5.04027374e-04, 2.95312792e-03, 7.58703821e-04,
        2.59777550e-03, 1.50583335e-03, 2.32597683e-03, 4.47751529e-04,
        2.47465617e-03, 7.58119596e-04, 2.46964844e-03, 6.02382733e-04,
        3.36344464e-03, 4.77178142e-04, 2.48472828e-03, 4.99116375e-04,
        5.16391033e-04, 4.98635185e-04, 3.94117418e-04, 2.90427104e-05,
        3.74779003e-04, 3.51254479e-04, 4.26682549e-04, 4.48752663e-05,
        6.41428676e-04, 4.18109887e-04, 2.35330611e-05, 4.96862122e-04,
        4.19976736e-04, 3.92985470e-04, 2.02107057e-04, 4.08376226e-04,
        4.07612982e-04, 4.11203901e-04, 3.25406338e-05, 2.69695151e-05,
        4.03551724e-04, 2.54546198e-05, 2.51991182e-05, 1.81338607e-05,
        4.79633240e-04, 4.36998818e-05, 1.71647296e-04, 1.12258446e-05,
        4.17583743e-04, 4.20701251e-04, 4.58597740e-04, 3.94242186e-04,
        2.12576714e-03, 8.22074991e-04, 2.76995430e-03, 1.43001632e-03,
        1.37905825e-03, 6.86906073e-04, 1.86151460e-03, 3.62586718e-04,
        1.93750592e-03, 4.13170572e-03, 1.94335005e-03, 3.97028032e-03,
        2.00979456e-03, 4.09258045e-03, 9.82631333e-04, 4.02317247e-03,
        9.47630646e-04, 6.70342799e-04, 8.92660093e-04, 4.02333578e-04,
        1.32164618e-03, 4.32757792e-04, 1.14990166e-03, 4.69906643e-04,
        2.18788728e-03, 4.56074165e-04, 2.04558526e-03, 4.17751823e-04,
        2.76207948e-03, 1.02672619e-04, 2.52024760e-03, 4.22631278e-04,
        4.13263861e-03, 1.02542170e-03, 2.37594432e-03, 2.33778023e-03,
        2.91532279e-03, 6.56102060e-04, 3.85279226e-03, 7.79352874e-04,
        2.40610648e-03, 7.17782127e-04, 1.65661670e-03, 1.41460616e-03,
        2.77738599e-03, 9.10034223e-04, 2.53545050e-03, 8.53339985e-04,
        4.34177249e-03, 7.47232318e-04, 4.29987788e-03, 4.03854235e-04,
        3.34843000e-03, 4.70901534e-04, 3.45520778e-03, 6.90362898e-04,
        2.39995193e-03, 3.72925861e-03, 2.84243916e-03, 3.68963380e-03,
        1.83066496e-03, 3.79953764e-03, 7.02436617e-03, 3.86955645e-03,
        3.76418575e-04, 5.11732774e-04, 1.47457094e-04, 3.81358709e-04,
        4.04590200e-04, 4.70950348e-04, 4.89823979e-04, 7.25137478e-06,
        4.01885191e-04, 4.04930480e-04, 4.03913116e-04, 3.99211492e-04,
        4.88023895e-04, 3.94680469e-04, 4.46901050e-04, 2.17958556e-04,
        3.89455750e-04, 4.59846670e-04, 4.08577607e-04, 3.73941373e-04,
        2.77562048e-04, 3.60659150e-05, 4.70586902e-04, 3.77441518e-04,
        3.79943159e-04, 3.98428848e-04, 5.16867316e-04, 4.69840271e-04,
        3.73853907e-04, 3.99721347e-04, 5.07599258e-04, 3.99683546e-04,
        2.49832937e-03, 5.58744984e-04, 2.53566081e-03, 1.45409318e-03,
        2.14543090e-03, 5.80170680e-04, 3.24853883e-03, 6.41578033e-04,
        2.94980393e-03, 5.35763211e-03, 2.78895276e-03, 5.20249617e-03,
        3.63017893e-03, 4.88305670e-03, 1.38955354e-03, 5.16264587e-03,
        4.94880205e-03, 4.69417675e-04, 4.89494020e-03, 5.00733304e-04,
        5.11788417e-03, 4.15310257e-04, 4.59098344e-03, 5.01289735e-04,
        1.88689333e-03, 7.01424844e-04, 2.35931672e-03, 5.02003951e-04,
        2.45370705e-03, 4.43395246e-04, 2.52321193e-03, 5.21027702e-04,
        1.62823575e-03, 1.53402703e-03, 4.00186573e-03, 8.49296811e-04,
        4.97619011e-03, 3.00927011e-03, 2.55997872e-03, 3.52744960e-04,
        2.72976513e-03, 6.63763103e-04, 7.24827989e-03, 1.68724156e-03,
        2.63709366e-03, 6.26523152e-04, 1.63299245e-03, 1.73070903e-03,
        2.65608642e-03, 2.06771923e-03, 2.31937621e-03, 3.00292268e-03,
        3.40427522e-03, 5.95006579e-03, 6.50237047e-03, 3.00288924e-03,
        2.75848476e-03, 6.12452724e-04, 3.44497298e-03, 1.42225258e-03,
        5.47016686e-03, 9.94853346e-04, 4.05127217e-03, 7.61063484e-04,
        4.05525947e-04, 5.17854273e-04, 9.36156555e-06, 2.16329042e-04,
        4.79711273e-04, 4.40342012e-05, 3.95640230e-04, 4.00928811e-04,
        3.97953237e-04, 2.30699632e-04, 4.12914769e-04, 5.19434950e-04,
        4.32738257e-04, 2.75744667e-05, 4.04488721e-04, 4.08839901e-04,
        4.53763777e-04, 3.99748934e-04, 3.68686272e-04, 7.77697870e-07,
        4.00662518e-04, 3.94088386e-04, 1.71172426e-04, 3.98409291e-04,
        4.07882352e-04, 5.00056175e-04, 5.07388625e-04, 3.63531393e-04,
        5.77324874e-04, 3.99057534e-04, 5.14497063e-04, 3.75196936e-04,
        8.65744783e-04, 4.36374148e-04, 6.77566458e-04, 4.51325058e-04,
        9.33270644e-04, 4.05448301e-04, 6.95655205e-04, 4.07507820e-04,
        6.01779345e-04, 1.85381542e-03, 5.34476652e-04, 6.82677786e-04,
        5.06145517e-04, 6.85925116e-04, 5.52941425e-04, 3.64598391e-04,

In [ ]:
results=pd.DataFrame(gridsearch.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002407,0.000494,0.000000,0.000000,gini,None,auto,1,2,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
1,0.002190,0.000441,0.000000,0.000000,gini,None,auto,1,2,random,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
2,0.002632,0.000492,0.000000,0.000000,gini,None,auto,1,3,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
3,0.002497,0.000448,0.000000,0.000000,gini,None,auto,1,3,random,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
4,0.002623,0.000786,0.000000,0.000000,gini,None,auto,1,5,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,0.019540,0.000590,0.003626,0.000516,entropy,20,log2,7,3,random,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.845556,0.842778,0.824861,0.841806,0.824028,0.835806,0.009361,146
764,0.098581,0.001659,0.003626,0.000454,entropy,20,log2,7,5,best,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.836111,0.845833,0.836111,0.844306,0.835694,0.839611,0.004485,101
765,0.020509,0.001312,0.003621,0.000502,entropy,20,log2,7,5,random,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.845556,0.842778,0.824861,0.841806,0.824028,0.835806,0.009361,146
766,0.099315,0.001007,0.003605,0.000479,entropy,20,log2,7,7,best,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.836111,0.845833,0.836111,0.844306,0.835694,0.839611,0.004485,101
767,0.020716,0.000619,0.003800,0.000405,entropy,20,log2,7,7,random,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.845556,0.842778,0.824861,0.841806,0.824028,0.835806,0.009361,146

In [ ]:
results.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
650,0.075347,0.002389,0.003992,0.000024,entropy,10,log2,3,3,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.855139,0.864167,0.850278,0.853750,0.851111,0.854889,0.004959,1
652,0.073518,0.004761,0.003420,0.000490,entropy,10,log2,3,5,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.855139,0.864167,0.850278,0.853750,0.851111,0.854889,0.004959,1
648,0.075045,0.004675,0.003607,0.000494,entropy,10,log2,3,2,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.855139,0.864167,0.850278,0.853750,0.851111,0.854889,0.004959,1
664,0.071834,0.001443,0.003186,0.000373,entropy,10,log2,7,2,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.851944,0.857917,0.853472,0.858194,0.850000,0.854306,0.003255,4
668,0.072914,0.001584,0.003211,0.000398,entropy,10,log2,7,5,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.851944,0.857917,0.853472,0.858194,0.850000,0.854306,0.003255,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,0.002010,0.000012,0.000000,0.000000,gini,None,auto,7,5,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
27,0.001828,0.000411,0.000000,0.000000,gini,None,auto,7,3,random,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
26,0.002114,0.000468,0.000000,0.000000,gini,None,auto,7,3,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
25,0.001990,0.000016,0.000000,0.000000,gini,None,auto,7,2,random,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
24,0.002030,0.000031,0.000000,0.000000,gini,None,auto,7,2,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513

In [ ]:
preprocessing = ColumnTransformer(
    transformers =[
        ('encoder',OneHotEncoder(handle_unknown='ignore', sparse_output=False),num_cols)
        
        
    ],remainder='passthrough'
)
# preprocessing.fit_transform(xtrain)


main_pipeline= Pipeline(
    steps=[
        ('pre',preprocessing),
        ('model', DecisionTreeClassifier(
            random_state=42,
            criterion='entropy',
            max_depth=100
            ))
    ]
    
)
main_pipeline.fit(xtrain,ytrain)

In [ ]:
# TRAIN DATA
ytrain_pred= model.predict(xtrain)

In [ ]:
# TEST DATA
ytest_pred= model.predict(xtest)