In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, root_mean_squared_error

In [2]:
df=pd.read_csv('Student_Performance1.csv')
df.corr(numeric_only=True)

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.012390,0.001245,0.017463,0.373730
Previous Scores,-0.012390,1.000000,0.005944,0.007888,0.915189
Sleep Hours,0.001245,0.005944,1.000000,0.003990,0.048106
Sample Question Papers Practiced,0.017463,0.007888,0.003990,1.000000,0.043268
Performance Index,0.373730,0.915189,0.048106,0.043268,1.000000

In [3]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [4]:
df['Extracurricular Activities']=df['Extracurricular Activities'].map({'Yes':1,'No':0})

In [5]:
x=df.drop(columns=['Performance Index',])
y=df['Performance Index']

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42) #explain random state # interview question

In [7]:
model=LinearRegression()

In [8]:
model.fit(x_train,y_train)

LinearRegression()

In [9]:
model.intercept_

np.float64(-33.92194621555611)

INTERCEPT CONCLUSION

BASED ON INITIAL VALUE OF PERMORMANCE INDEX IS -33.92194621555611 WHEN ALL FEATURES EQUALS TO ZERO.

In [10]:
model.coef_ # rate of change of performance index with respect to hours studied by 1 unit is 2.85248393.
            # rate of change of permormance index with respect to previous scores by 1 unit is 1.0169882.
            # rate of change of performance index with respect to extracurricular activities by 1 unit is 0.60861668.
            # rate of change of permormance index with respect to sample question papers practised by 1 unit is 0.47694148.
            # rate of change of performance index 
            
            
# error= actual output- predicted output

array([2.85248393, 1.0169882 , 0.60861668, 0.47694148, 0.19183144])

In [11]:
# ytrain(actual)
# ytrain_predicted(predicted_values)
'''
syntax
model.predict(x)
ytrain_predicted=model.predict(x_train)
ytest_predicted=model.predict(x_test)'''
ytrain_predicted= model.predict(x_train)

In [12]:
'''syntax for metrics
metricname(actualoutput,predictedoutput)
for r2_score?
r2_score(y_train,ytrain_predicted)
r2_score(y_test,ytest_predicted)'''

'syntax for metrics\nmetricname(actualoutput,predictedoutput)\nfor r2_score?\nr2_score(y_train,ytrain_predicted)\nr2_score(y_test,ytest_predicted)'

In [13]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [14]:
r2_score(y_train,ytrain_predicted)

0.9886898790682355

In [15]:
mean_absolute_error(y_train,ytrain_predicted)

1.6193054830334277

In [16]:
root_mean_squared_error(y_train,ytrain_predicted)

2.0419931071198567

# MODEL EVALUATION