In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
df=pd.read_csv('Student_Performance1.csv')
df.corr(numeric_only=True)
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [4]:
y_train = y_train.map({'Yes': 1, 'No': 0})

NameError: name 'y_train' is not defined

In [ ]:
x=df.drop(columns=['Performance Index'])
y=df['Performance Index']

In [ ]:
df.shape

(10000, 6)

# UNPACKING

In [ ]:
# train-test-split method returns list of 4 values, so we can unpack them into 4 variables.
# first 2 values belongs to x and last 2 values belongs to y.
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=42)

In [ ]:
x_train
# each time the sample data is changing, that will affect our accuracy of the model.
# to fix this we can use random_state parameter, which will fix the sample data and will not change it.

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
9254,5,49,No,7,5
1561,2,48,Yes,7,6
1670,2,81,No,7,2
6087,2,46,No,6,1
6669,8,47,No,9,0
...,...,...,...,...,...
5734,8,50,Yes,6,6
5191,4,68,No,9,3
5390,9,48,No,7,6
860,1,47,No,9,0
7270,2,46,No,6,6

In [ ]:
y_train

9254    36.0
1561    25.0
1670    59.0
6087    22.0
6669    40.0
        ...
5734    48.0
5191    51.0
5390    44.0
860     20.0
7270    24.0
Name: Performance Index, Length: 8000, dtype: float64

# MODEL CREATION

In [ ]:
model=LinearRegression()

# MODEL TRAINING

In [ ]:
print(x_train.dtypes)

Hours Studied                        int64
Previous Scores                      int64
Extracurricular Activities          object
Sleep Hours                          int64
Sample Question Papers Practiced     int64
dtype: object

In [ ]:
model.fit(x_train, y_train)

NameError: name 'model' is not defined